&base_mesh
f_lat_deg=45.0,
file_prefix='input_mesh_faces',
fplane=.false.,
geometry='spherical',
prepartitioned=.false.,
prime_mesh_name='dynamics',
topology='fully_periodic',
/
&extrusion
domain_height=80000.0,
method='um_L70_50t_20s_80km',
number_of_layers=70,
planet_radius=6371229.0,
/
&finite_element
cellshape='quadrilateral',
coord_order=1,
coord_order_nonprime=1,
coord_space='Wchi',
coord_system='native',
element_order_h=0,
element_order_v=0,
rehabilitate=.true.,
vorticity_in_w1=.true.,
/
&planet
cp=1005.0,
gravity=9.80665,
omega=7.292116E-5,
p_zero=100000.0,
rd=287.05,
scaling_factor=125.0,
/
&partitioning
generate_inner_halos=.true.,
panel_decomposition='auto',
panel_xproc=3,
panel_yproc=4,
partitioner='cubedsphere',
/
&formulation
l_multigrid=.false.,
use_multires_coupling=.false.,
use_physics=.true.,
/
&io
checkpoint_read=.false.,
checkpoint_write=.false.,
counter_output_suffix='counter.txt',
diagnostic_frequency=1,
file_convention='UGRID',
nodal_output_on_w3=.false.,
subroutine_counters=.false.,
subroutine_timers=.false.,
timer_output_path='timer.txt',
use_xios_io=.true.,
write_diag=.false.,
/
&time
calendar='timestep',
calendar_origin='2016-01-01 15:00:00',
calendar_start='2016-01-01 15:00:00',
calendar_type='gregorian',
timestep_end='1',
timestep_start='1',
/
&timestepping
dt=1.0,
/
&logging
run_log_level='info',
/
